#!/usr/bin/env bash
set -euo pipefail

repo="hand-university/zwitch"
pkgname="zwitch-bin"
version="latest"
pkgrel="1"
output_dir="build/aur/${pkgname}"
build_package=1
install_package=0
clean_output=0

usage() {
  cat <<'EOF'
Build a local Arch/AUR package for ZWitch from the GitHub release .deb.

Usage:
  scripts/build-aur-package.sh [options]

Options:
  --version <version>     Release version or tag. Defaults to latest.
                          Examples: 0.1.5, v0.1.5
  --pkgrel <number>      Arch pkgrel. Defaults to 1.
  --output-dir <path>    Directory for generated PKGBUILD/.SRCINFO.
                          Defaults to build/aur/zwitch-bin.
  --no-build             Only generate PKGBUILD and .SRCINFO.
  --install              Run makepkg -fsi after generating.
  --clean                Remove the output directory before generating.
  -h, --help             Show this help.

Examples:
  scripts/build-aur-package.sh
  scripts/build-aur-package.sh --version 0.1.5 --install
  scripts/build-aur-package.sh --no-build
EOF
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

need() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version)
      [[ $# -ge 2 ]] || die "--version requires a value"
      version="$2"
      shift 2
      ;;
    --pkgrel)
      [[ $# -ge 2 ]] || die "--pkgrel requires a value"
      pkgrel="$2"
      shift 2
      ;;
    --output-dir)
      [[ $# -ge 2 ]] || die "--output-dir requires a value"
      output_dir="$2"
      shift 2
      ;;
    --no-build)
      build_package=0
      shift
      ;;
    --install)
      install_package=1
      build_package=1
      shift
      ;;
    --clean)
      clean_output=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
done

need curl
need jq
need makepkg

if [[ "$version" == "latest" ]]; then
  release_api="https://api.github.com/repos/${repo}/releases/latest"
else
  tag="$version"
  [[ "$tag" == v* ]] || tag="v${tag}"
  release_api="https://api.github.com/repos/${repo}/releases/tags/${tag}"
fi

printf 'Fetching release metadata: %s\n' "$release_api"
release_json="$(curl -fsSL "$release_api")"

tag_name="$(jq -r '.tag_name // empty' <<<"$release_json")"
[[ -n "$tag_name" ]] || die "release response did not contain tag_name"

pkgver="${tag_name#v}"
asset_name="ZWitch_${pkgver}_amd64.deb"

asset_json="$(
  jq -c --arg name "$asset_name" '
    .assets[]? | select(.name == $name)
  ' <<<"$release_json"
)"

if [[ -z "$asset_json" ]]; then
  printf 'Available release assets:\n' >&2
  jq -r '.assets[]?.name | "  - \(.)"' <<<"$release_json" >&2
  die "could not find Linux amd64 deb asset: ${asset_name}"
fi

asset_url="$(jq -r '.browser_download_url' <<<"$asset_json")"
sha256="$(jq -r '.digest // empty' <<<"$asset_json" | sed 's/^sha256://')"

if [[ ! "$sha256" =~ ^[0-9a-fA-F]{64}$ ]]; then
  tmp_file="$(mktemp)"
  trap 'rm -f "$tmp_file"' EXIT
  printf 'GitHub release did not expose a sha256 digest; downloading once to compute it...\n'
  curl -fL -o "$tmp_file" "$asset_url"
  sha256="$(sha256sum "$tmp_file" | awk '{print $1}')"
fi

if (( clean_output )); then
  rm -rf "$output_dir"
fi

mkdir -p "$output_dir"

cat > "${output_dir}/PKGBUILD" <<PKGBUILD
# Maintainer: ZWitch maintainers
# Generated by scripts/build-aur-package.sh from ${repo} ${tag_name}.
pkgname=${pkgname}
pkgver=${pkgver}
pkgrel=${pkgrel}
pkgdesc='ZWitch - AI CLI proxy configuration tool'
arch=('x86_64')
url='https://github.com/${repo}'
license=('custom')
depends=('gtk3' 'webkit2gtk-4.1' 'libayatana-appindicator')
provides=('zwitch')
conflicts=('zwitch')
options=('!strip' '!debug')
source=("\${pkgname}-\${pkgver}.deb::${asset_url}")
noextract=("\${pkgname}-\${pkgver}.deb")
sha256sums=('${sha256}')

package() {
  bsdtar -xf "\${srcdir}/\${pkgname}-\${pkgver}.deb" -C "\${srcdir}" data.tar.gz
  bsdtar -xzf "\${srcdir}/data.tar.gz" -C "\${pkgdir}"

  chmod 755 "\${pkgdir}/usr/bin/zwitch"

  if [[ -f "\${pkgdir}/usr/share/applications/ZWitch.desktop" ]]; then
    sed -i 's/^Categories=.*/Categories=Utility;/' "\${pkgdir}/usr/share/applications/ZWitch.desktop"
  fi
}
PKGBUILD

(
  cd "$output_dir"
  makepkg --printsrcinfo > .SRCINFO
)

printf 'Generated %s/PKGBUILD\n' "$output_dir"
printf 'Generated %s/.SRCINFO\n' "$output_dir"

if (( build_package )); then
  (
    cd "$output_dir"
    if (( install_package )); then
      makepkg -fsi
    else
      makepkg -f
    fi
  )

  pkgfile="$(
    find "$output_dir" -maxdepth 1 -type f \
      -name "${pkgname}-${pkgver}-${pkgrel}-*.pkg.tar.*" \
      | sort \
      | tail -n 1
  )"

  if [[ -n "$pkgfile" ]]; then
    printf 'Built package: %s\n' "$pkgfile"
  fi
fi
